name: cuba_weather
description: Application for mobile devices of the Cuba Weather project implemented with Flutter

version: 1.4.0+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cuba_weather_dart: ^3.1.1
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  shared_preferences: ^0.5.6
  autocomplete_textfield: ^1.7.3
  package_info: ^0.4.0+13
  url_launcher: ^5.4.1
  getflutter: ^1.0.9
  weather_icons: ^2.0.0
  share: ^0.6.3+5
  font_awesome_flutter: ^8.5.0
  flutter_speed_dial: ^1.2.5
  geolocator: ^5.2.1
  preferences: ^5.1.0
  flutter_swiper : ^1.1.6
  charts_flutter: ^0.9.0
  provider: ^4.0.4
  story_view: ^0.11.4
  flutter_whatsnew: ^1.0.3

flutter:

  uses-material-design: true

  assets:
    - CHANGELOG.md
    - images/
    - images/radar/
    - images/satellite/
